### ISSUE TITLE
[Statistical issue; proposal] Changing the SEs to CIs or SDs

### ISSUE THREAD

**Issue by Generalized** [kbelisar/ggcorset#2]
Dear @kbelisar 
Thank you for making this package. These plots are very eye-catching. I like it.

But let me, please, kindly ask you to consider changing the SEs to either SD (for description) or CIs (for inference). SEs itself has no direct application in statistical inference, as no distribution of the test statistic is employed.

SE, measuring the precision of sampling, itself is just a semi-product, used to calculate the confidence intervals depending **on the used distribution**. The SE itself says nothing about the comparison as long as we don't pick the right distribution - and this distribution doesn't have to be even symmetric, like chi2, F, non-central T.

As a consequence - **for the same SE** we may have **(very) different CIs**, **depending on the used test statistic**. This may result in **different result of testing for the same SE**.

Unfortunately to science, researchers:
1) routinely naively look for overlap of SEs to compare groups, which leads to wrong conclusions. SEs are just too short, so _the lack of overlap doesn't necessarily mean statistical significance_. Actually, comparing group CIs is also wrong (wrong SD is used) - oppositely they are too long so _overlapping doesn't necessarily mean lack of stat. significance_. The only CI that makes sense for the inference on comparing groups is the CI of the difference or ratio.

2) even worse - they often "abuse" SEs by making use of the fact, that SEs are shorter than CIs (SE is "expanded" to a CI through the quantile of the test statistic distribution ), which is used to "show up" the effect and cheat that it is "better visible".

Given the above arguments, would you be willing to change SE to CI?

In the simplest case - by assuming the t-distribution.
Ideally - flexibly: by allowing the user to specify the distribution of interest or BCa bootstrap, by returning the by default the BCa (bias corrected and accelerated) CIs, which, if failed, are calculated as percentile CIs.

**Comment by kbelisar** [comment]
Dear @Generalized ,

Thank you for your kind comment and suggestion. I appreciate you taking the time to write in-depth reasoning for the use of SD or CIs instead of SE. I agree that SE is often used incorrectly to infer significant differences between means, and this is not the intent of use in the 'ggcorset' package (nor do I recommend its use in this manner). Rather, the analyst should explore these group differences themselves, applying the appropriate test (if desired).

With that said, I think there is merit in keeping SE to better understand the "precision" of the sample mean relative to sample size (se = sd / $\sqrt{n}$ ). I also think that offering an alternative 'eyelet type' (one of SD) would be best for statistical integrity. Specifically, I think by offering both SD and SE (in a clear manner), will help to combat against uses as you mentioned in points 1 and 2. 

I appreciate your suggestion to provide CIs by using a flexible approach (and I appreciate your creative solution to providing this flexibility). At this time, it is beyond the scope of the package. I will, however, keep it in mind for future versions if the demand/ need is there. In the meantime, since the 'eyelet' feature is optional, user-defined CIs could be added to the visualization as both 'ggcorset' functions return a 'ggplot2' object.

Again, thank you for bringing attention to this. I will work to add the SDs to the GitHub version of the package, and will close this comment once this is completed.

**Comment by kbelisar** [comment]
This enhancement has been made by adding an `e_type` argument to both gg_corset() and gg_corset_elongated() functions. To visualize 1 standard deviation above and below the mean instead of standard error means, the argument `e_type` = "SD" needs to be specified. Further documentation has been added to the README of this repository.
