### ISSUE TITLE
custom colour for reference lines 

### ISSUE THREAD

**Issue by aghaynes** [kbelisar/ggcorset#3]
This is a great data viz tool! Well done. 

I have a suggestion related to the (currently grey) reference lines... 

It would be nice to be able to give them a custom colour, or even remove them entirely. 

https://github.com/kbelisar/ggcorset/blob/c3e09fdd9b6b97007c6d860d96f15e9a35590cc7/R/gg_corset.R#L180

It would probably just be a case of a new option set to the current `#B3B3B3`...

I can make a PR if you like?

**Comment by kbelisar** [comment]
Hello, thank you so much for your feedback!

I appreciate the offer to make a PR, but I'm going to go ahead and work on this since I have another features in the works that would probably make sense to set up in the same argument.

For now, I will add a feature to allow for basic facets (i.e. no non-reference grey lines) as well as an option to customize the colour of these lines. I hope to push this to GH later this week.

**Comment by aghaynes** [comment]
Thanks for doing this so fast! My collaborators found the grey lines confusing, so this should make them happy... and it was just in time for a report too! 
Thanks again!
